Added a component to simulate simple sheets of cloth
ezEngine/ezEngine pull request #453
Opened 2021-08-11 15:55 UTC by jankrassnigg

2021-08-11 19:14 UTC, C-Core requested changes

2021-08-11 19:14 UTC, C-Core commented on Code/Engine/RendererCore/Meshes/Implementation/DynamicMeshBufferResource.cpp
> +    si.m_Format = ezGALResourceFormat::XYZFloat;
This should be ezGALResourceFormat::XYZWFloat and sizeof(ezVec4) below

2021-08-11 19:14 UTC, C-Core commented on Code/Engine/RendererCore/Meshes/Implementation/DynamicMeshBufferResource.cpp
> +  // TODO: can ezGALUpdateMode::Discard be used, if only a subset is updated (without destroying existing data) ?
No discard literally means "discard existing data". If you update only a subset but don't want to destroy existing data you need to use CopyToTempStorage

2021-08-11 19:14 UTC, C-Core commented on Code/Engine/RendererCore/Meshes/Implementation/DynamicMeshBufferResource.cpp
> +void ezDynamicMeshVertex::EncodeNormal(const ezVec3& normal)
Maybe make these inline to save the function call. Or you make this a batch processing function.

2021-08-11 20:41 UTC, jankrassnigg commented on Code/Engine/RendererCore/Meshes/Implementation/DynamicMeshBufferResource.cpp
> +void ezDynamicMeshVertex::EncodeNormal(const ezVec3& normal)
batch processing isn't easy here, though you do get public access to the actual data, in case the calling code can implement that itself

2021-08-12 06:59 UTC, C-Core approved these changes

2021-08-12 07:04 UTC, merged